# fly.toml app configuration file generated for pandidorty-cz-test on 2025-05-26T09:55:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pandidorty-cz-test'
primary_region = 'fra'

[build]

[env]
  HOST = "0.0.0.0"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
